### ISSUE TITLE
Error: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by timpulver** [ob1y2k/publitio_js_sdk#10]
When trying out the example from the Readme with a 90MB wav file I get the following error:
```
{ Error: Request body larger than maxBodyLength limit
    at RedirectableRequest.write (/some/path/node_modules/follow-redirects/index.js:97:24)
    at RedirectableRequest.end (/some/path/node_modules/follow-redirects/index.js:116:8)
    at dispatchHttpRequest (/some/path/node_modules/axios/lib/adapters/http.js:272:11)
    at new Promise (<anonymous>)
    at httpAdapter (/some/path/node_modules/axios/lib/adapters/http.js:20:10)
    at dispatchRequest (/some/path/node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
    ...
```

According to this [axios discussion](https://github.com/axios/axios/issues/1362) it might be easy to fix by increasing the maximum content length (in bytes):
```
maxContentLength: 524288900 // 500MB
```

**Comment by ennmichael** [comment]
Hi @timpulver, thanks for opening this issue!
This was fixed in version 1.1.1. Try updating your dependency, and it should work.
